# vim:set ft=tmux:

# --> Catppuccin (Mocha)
set -ogq @thm_bg "#1e1e2e"
set -ogq @thm_fg "#d2e5ff"

# Colors
set -ogq @thm_rosewater "#f5e0dc"
set -ogq @thm_flamingo "#f2cdcd"
set -ogq @thm_pink "#f5c2e7"
set -ogq @thm_mauve "#9c5af0"
set -ogq @thm_red "#e3455c"
set -ogq @thm_maroon "#ef91d6"
set -ogq @thm_peach "#ef7938"
set -ogq @thm_yellow "#e2b75e"
set -ogq @thm_green "#76c65c"
set -ogq @thm_teal "#94e2d5"
set -ogq @thm_sky "#89dceb"
set -ogq @thm_sapphire "#65c7b8"
set -ogq @thm_blue "#739df2"
set -ogq @thm_lavender "#b4befe"

# Surfaces and overlays
set -ogq @thm_subtext_1 "#a6adc8"
set -ogq @thm_subtext_0 "#bac2de"
set -ogq @thm_overlay_2 "#9399b2"
set -ogq @thm_overlay_1 "#7f849c"
set -ogq @thm_overlay_0 "#6c7086"
set -ogq @thm_surface_2 "#585b70"
set -ogq @thm_surface_1 "#45475a"
set -ogq @thm_surface_0 "#313244"
set -ogq @thm_mantle "#181825"
set -ogq @thm_crust "#11111b"

